sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rfldocker2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rfldocker2020/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-779341231822"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
